---
Name: dd_ss_routes
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#googlesitemaproutes'
---
SilverStripe\Control\Director:
  rules:
    search: DD\Client\SilverStripe\Controller\SearchPageController
